- name: install nginx server
  hosts: all
  become: yes
  serial: 3 #connects 3servers from n-servers and connect-3 servers + task-1 on 3servers + task-2 on 3servers...repeat same steps till n-servers
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx 
      state: present
  
  - name: start nginx
    anaible.builtin.service:
      name: nginx
      state: started
      enabled: yes
